// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recetario_Api;

#nullable disable

namespace Recetario_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260913020406_Cambiosunidad")]
    partial class Cambiosunidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Recetario_Api.Entities.Ingrediente", b =>
                {
                    b.Property<int>("IngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IngredienteId");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("Recetario_Api.Entities.IngredienteReceta", b =>
                {
                    b.Property<int>("IngredienteRecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<int>("Recetaid")
                        .HasColumnType("int");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.HasKey("IngredienteRecetaId");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("Recetaid");

                    b.HasIndex("UnidadId");

                    b.ToTable("IngredienteReceta");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Paso", b =>
                {
                    b.Property<int>("PasoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroPasos")
                        .HasColumnType("int");

                    b.Property<int>("RecetaId")
                        .HasColumnType("int");

                    b.HasKey("PasoId");

                    b.HasIndex("RecetaId");

                    b.ToTable("Paso");
                });

            modelBuilder.Entity("Recetario_Api.Entities.PreferenciaAlimentaria", b =>
                {
                    b.Property<int>("PreferenciaAlimentariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PreferenciaAlimentariaId");

                    b.ToTable("PreferenciaAlimentaria");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Receta", b =>
                {
                    b.Property<int>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Horno")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Porciones")
                        .HasColumnType("int");

                    b.Property<int>("PreferenciaAlimentariaId")
                        .HasColumnType("int");

                    b.Property<int>("TiempoPreparacionMin")
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("RecetaId");

                    b.HasIndex("PreferenciaAlimentariaId");

                    b.HasIndex("TipoId");

                    b.ToTable("Receta");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Tipo", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TipoId");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Unidad", b =>
                {
                    b.Property<int>("UnidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Unidades")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UnidadId");

                    b.ToTable("Unidad");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Utensilio", b =>
                {
                    b.Property<int>("UtensilioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("RecetaId")
                        .HasColumnType("int");

                    b.Property<string>("Utensilios")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UtensilioId");

                    b.HasIndex("RecetaId");

                    b.ToTable("Utensilio");
                });

            modelBuilder.Entity("Recetario_Api.Entities.IngredienteReceta", b =>
                {
                    b.HasOne("Recetario_Api.Entities.Ingrediente", "Ingrediente")
                        .WithMany("Recetas")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetario_Api.Entities.Receta", "Receta")
                        .WithMany("Ingredientes")
                        .HasForeignKey("Recetaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetario_Api.Entities.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Receta");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Paso", b =>
                {
                    b.HasOne("Recetario_Api.Entities.Receta", "Receta")
                        .WithMany("PasosL")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Receta", b =>
                {
                    b.HasOne("Recetario_Api.Entities.PreferenciaAlimentaria", "PreferenciaAlimentaria")
                        .WithMany("Recetas")
                        .HasForeignKey("PreferenciaAlimentariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetario_Api.Entities.Tipo", "Tipo")
                        .WithMany("Recetas")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreferenciaAlimentaria");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Utensilio", b =>
                {
                    b.HasOne("Recetario_Api.Entities.Receta", "Receta")
                        .WithMany("Utensilios")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Ingrediente", b =>
                {
                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("Recetario_Api.Entities.PreferenciaAlimentaria", b =>
                {
                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Receta", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("PasosL");

                    b.Navigation("Utensilios");
                });

            modelBuilder.Entity("Recetario_Api.Entities.Tipo", b =>
                {
                    b.Navigation("Recetas");
                });
#pragma warning restore 612, 618
        }
    }
}
